'''
Constants
'''

from importlib.resources import files


TOMATO_MODEL_FILENAME = "" #FIXME
RICE_MODEL_FILENAME = "" #FIXME
POTATO_MODEL_FILENAME = "" #FIXME

MODELS_BASE_DIR = files("plant_scanner.assets")

RICE_MODEL_PATH = MODELS_BASE_DIR.joinpath(RICE_MODEL_FILENAME)
TOMATO_MODEL_PATH = MODELS_BASE_DIR.joinpath(TOMATO_MODEL_FILENAME)
POTATO_MODEL_PATH = MODELS_BASE_DIR.joinpath(POTATO_MODEL_FILENAME)
